# Generated by Django 5.1.4 on 2026-05-05 22:31

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="My portfolio", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Available cash. Updated atomically on deposits/withdrawals/orders.",
                        max_digits=18,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
