# Generated by Django 5.1.4 on 2026-05-05 22:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Always stored as a positive number; ``kind`` carries the sign.",
                        max_digits=18,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_transactions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "-transaction_date"],
                        name="transaction_portfol_b70063_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=8
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Snapshot of the unit price at execution time.",
                        max_digits=18,
                    ),
                ),
                ("executed_at", models.DateTimeField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "-executed_at"],
                        name="transaction_portfol_09fe3c_idx",
                    ),
                    models.Index(
                        fields=["portfolio", "symbol"],
                        name="transaction_portfol_91a44e_idx",
                    ),
                ],
            },
        ),
    ]
